name: Test Bundle Builds

on: [pull_request, push]

jobs:
  test-bundle-builds:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - name: Versions
        run: |
          python3 --version
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install deps
        run: |
          pip install -r requirements.txt
      - name: Test building bundle
        run: |
          BUILD_SUCCESS=false
          # Use the community bundle because it's smaller and faster
          git clone --recurse-submodules https://github.com/adafruit/CircuitPython_Community_Bundle.git
          cd CircuitPython_Community_Bundle
          circuitpython-build-bundles --filename_prefix test-bundle --library_location libraries --library_depth 2
          BUILD_SUCCESS=true
    outputs:
      build_success: $BUILD_SUCCESS

  mock-push-updates:
    runs-on: ubuntu-latest
    needs: test-bundle-builds


    if: needs.test-bundle-builds.outputs.build_success
    steps:
      - name: Check For Success
        run: echo "The builds were successful!"